"""Parameter space sampling for PINN training data generation.

Defines the configuration schema for sweeping material parameters and
provides a Latin Hypercube Sampling implementation (requires no external
dependency — pure Python with the ``random`` module).

Example usage::

    from orchard_pinn.data.parameter_space import (
        ParameterRange,
        ParameterSpaceConfig,
        latin_hypercube_sample,
    )
    from orchard_fem.workflows.batch_excitation import ExcitationSpec

    config = ParameterSpaceConfig(
        material_youngs_modulus_ranges={
            "xylem_default":  ParameterRange("xylem_E",  5.0e9, 2.0e10),
            "pith_default":   ParameterRange("pith_E",   3.0e8, 1.5e9),
        },
        fruit_mass_scale_range=ParameterRange("fruit_mass_scale", 0.5, 2.0),
        excitation_specs=[
            ExcitationSpec(branch_id="trunk",   node="tip", component="ux"),
            ExcitationSpec(branch_id="primary", node="tip", component="ux"),
        ],
        n_samples=50,
        seed=42,
    )
    samples = latin_hypercube_sample(config)
    # samples[i] is a dict {param_name: float_value} for the i-th design point
"""
from __future__ import annotations

import random
from dataclasses import dataclass, field
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from orchard_fem.workflows.batch_excitation import ExcitationSpec


@dataclass
class ParameterRange:
    """Uniform variation range for a single scalar parameter.

    Parameters
    ----------
    name:
        Human-readable identifier used as the dict key in sample dicts.
    low:
        Lower bound (inclusive).
    high:
        Upper bound (exclusive in LHS sense; samples are drawn from
        ``[low + k*(high-low)/n, low + (k+1)*(high-low)/n]`` strata).
    """

    name: str
    low: float
    high: float

    def __post_init__(self) -> None:
        if self.low >= self.high:
            raise ValueError(
                f"ParameterRange '{self.name}': low ({self.low}) must be less than high ({self.high})."
            )


@dataclass
class ParameterSpaceConfig:
    """Full configuration for a PINN training data generation run.

    Parameters
    ----------
    material_youngs_modulus_ranges:
        Mapping from material ID (e.g. ``"xylem_default"``) to its Young's
        modulus variation range [Pa].  Only materials whose IDs appear here
        will be perturbed; others keep the base model's material properties.
    fruit_mass_scale_range:
        Multiplicative scale factor applied uniformly to all fruit masses
        generated by the FruitDistributionPolicy.  A scale of 1.0 means no
        change; 0.5 halves all fruit masses.
    excitation_specs:
        List of excitation point specifications used for each batch run.
        All specs share the same assembled system for a given parameter sample.
    n_samples:
        Number of Latin Hypercube design points to generate.
    seed:
        Random seed for reproducibility.
    """

    material_youngs_modulus_ranges: dict[str, ParameterRange] = field(default_factory=dict)
    fruit_mass_scale_range: ParameterRange = field(
        default_factory=lambda: ParameterRange("fruit_mass_scale", 1.0, 1.0 + 1e-12)
    )
    excitation_specs: list[ExcitationSpec] = field(default_factory=list)
    n_samples: int = 10
    seed: int = 0

    def parameter_names(self) -> list[str]:
        """Return ordered list of all parameter names (material E's, then fruit mass scale)."""
        names = [r.name for r in self.material_youngs_modulus_ranges.values()]
        names.append(self.fruit_mass_scale_range.name)
        return names

    def parameter_ranges(self) -> list[ParameterRange]:
        """Return ordered list of all ParameterRange objects."""
        ranges = list(self.material_youngs_modulus_ranges.values())
        ranges.append(self.fruit_mass_scale_range)
        return ranges


def latin_hypercube_sample(config: ParameterSpaceConfig) -> list[dict[str, float]]:
    """Generate *n_samples* LHS design points from *config*.

    Pure Python implementation using the random module; no external dependency.

    Each parameter axis is divided into ``n_samples`` equal-width strata.
    One sample is drawn uniformly from within each stratum.  The column
    vectors are then shuffled independently so that the joint sample has
    good space-filling properties.

    Parameters
    ----------
    config:
        Sampling configuration.

    Returns
    -------
    list[dict[str, float]]
        Length-``n_samples`` list; each element is a dict mapping
        parameter name → sampled value.
    """
    n = config.n_samples
    if n <= 0:
        raise ValueError("n_samples must be positive.")

    rng = random.Random(config.seed)
    ranges = config.parameter_ranges()

    if not ranges:
        return [{} for _ in range(n)]

    # Draw one uniform value from each of the n strata for every parameter.
    # strata_values[param_index][stratum_index] = raw uniform ∈ [0, 1)
    strata_values: list[list[float]] = []
    for _ in ranges:
        column = [(k + rng.random()) / n for k in range(n)]
        rng.shuffle(column)
        strata_values.append(column)

    samples: list[dict[str, float]] = []
    for sample_index in range(n):
        sample: dict[str, float] = {}
        for param_index, param_range in enumerate(ranges):
            unit = strata_values[param_index][sample_index]
            value = param_range.low + unit * (param_range.high - param_range.low)
            sample[param_range.name] = value
        samples.append(sample)

    return samples
