name: orchard-fenicsx
channels:
  - conda-forge
dependencies:
  - python=3.11
  - dolfinx
  - petsc4py
  - slepc4py
  - mpi4py
  - numpy
  - scipy
  - pandas
  - h5py
  - pyyaml
  - matplotlib
  - scikit-image
  - jupyter
  - pytest
  - pytest-cov
  - ruff
  - mypy
  - pytorch
  - timm
# Optional and not installed by default:
#   - deepxde
